## Purpose

The purpose of this notebook is to perform data processing in order to investigate whether it rains more in Seattle, WA than in New York City, NY.

This notebook is apart of the first assignment for DATA-3320.

## Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style='whitegrid')
import missingno as msno

## Load data

The NOAA National Centers for Environmental Information provides access to many types of environmental data, including records of daily precipitation.

Their [website](https://www.ncei.noaa.gov/cdo-web/search?datasetid=GHCND) was used to request records of daily precipitation from Seattle and New York (or other locations of interest) for the 3 year period January 2020 - January 2024.

The data sets are available at this [github repository](https://github.com/galenegan/DATA-3320/tree/main/weather) and are called `seattle_rain.csv` and `ny_rain.csv`.

Load the Seattle data set

In [2]:
df_seattle = pd.read_csv('https://raw.githubusercontent.com/galenegan/DATA-3320/main/weather/seattle_rain.csv')

Load the New York data set

In [3]:
df_ny = pd.read_csv('https://raw.githubusercontent.com/galenegan/DATA-3320/main/weather/ny_rain.csv')

## Explore the Data

This code shows samples of some of the rows in the data sets, sees if the names of the columns are the same, and overall tries to examine whether or not these are appropriate data sets for our investigation.

In [4]:
# Look at head of each dataframe
df_seattle.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,DASF,MDSF
0,US1WAKG0199,"SEATTLE 4.5 N, WA US",47.686424,-122.362209,82.9,2020-01-01,NaN,NaN,0.19,NaN,NaN,NaN,NaN
1,US1WAKG0255,"SEATTLE 6.5 SSW, WA US",47.530849,-122.382541,135.0,2020-01-01,NaN,NaN,0.23,NaN,NaN,NaN,NaN
2,US1WAKG0243,"SEATTLE 3.9 SSW, WA US",47.567666,-122.372386,48.2,2020-01-01,NaN,NaN,0.19,NaN,NaN,NaN,NaN
3,US1WAKG0145,"SEATTLE 4.2 N, WA US",47.681873,-122.365539,74.1,2020-01-01,NaN,NaN,0.13,NaN,NaN,NaN,NaN
4,US1WAKG0192,"SEATTLE 5.6 N, WA US",47.702387,-122.351663,112.5,2020-01-01,NaN,NaN,0.22,NaN,NaN,NaN,NaN

In [5]:
df_seattle.describe()

,LATITUDE,LONGITUDE,ELEVATION,DAPR,MDPR,PRCP,SNOW,SNWD,DASF,MDSF
count,7003.000000,7003.000000,7003.000000,143.000000,143.000000,6718.000000,3006.000000,1331.000000,0.0,0.0
mean,47.593303,-122.322535,102.045666,5.776224,0.892098,0.132364,0.050000,0.172727,NaN,NaN
std,0.091807,0.023108,31.391744,6.723325,1.585583,0.270202,0.466821,0.960576,NaN,NaN
min,47.444670,-122.382541,37.200000,2.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,47.543999,-122.314420,74.100000,2.000000,0.080000,0.000000,0.000000,0.000000,NaN,NaN
50%,47.611700,-122.312907,112.500000,4.000000,0.420000,0.010000,0.000000,0.000000,NaN,NaN
75%,47.696532,-122.308500,121.300000,6.000000,1.000000,0.140000,0.000000,0.000000,NaN,NaN
max,47.702387,-122.303810,135.600000,53.000000,11.400000,3.010000,10.000000,11.000000,NaN,NaN

In [6]:
df_ny.head()

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,DASF,MDSF
0,USW00094728,"NY CITY CENTRAL PARK, NY US",40.778980,-73.969250,42.7,2020-01-01,NaN,NaN,0.00,0.0,0.0,NaN,NaN
1,US1NYWC0018,"ARMONK 0.3 SE, NY US",41.129960,-73.708161,117.3,2020-01-01,NaN,NaN,0.06,0.0,0.0,NaN,NaN
2,US1NYNS0034,"WANTAGH 0.3 ESE, NY US",40.666824,-73.505371,4.3,2020-01-01,NaN,NaN,0.00,0.0,0.0,NaN,NaN
3,USW00054787,"FARMINGDALE REPUBLIC AIRPORT, NY US",40.734430,-73.416370,22.8,2020-01-01,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1NYNS0042,"ALBERTSON 0.2 SSE, NY US",40.769131,-73.647484,43.3,2020-01-01,NaN,NaN,0.00,0.0,NaN,NaN,NaN

In [7]:
# See if the columns are the same
print(df_seattle.columns)
print(df_ny.columns)

Index(['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'DAPR',
       'MDPR', 'PRCP', 'SNOW', 'SNWD', 'DASF', 'MDSF'],
      dtype='object')
Index(['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'DAPR',
       'MDPR', 'PRCP', 'SNOW', 'SNWD', 'DASF', 'MDSF'],
      dtype='object')

In [8]:
set(df_seattle.columns) == set(df_ny.columns)

True

In [9]:
# Checking the types
df_seattle.dtypes

STATION       object
NAME          object
LATITUDE     float64
LONGITUDE    float64
ELEVATION    float64
DATE          object
DAPR         float64
MDPR         float64
PRCP         float64
SNOW         float64
SNWD         float64
DASF         float64
MDSF         float64
dtype: object

In [10]:
# Checking the types
df_ny.dtypes

STATION       object
NAME          object
LATITUDE     float64
LONGITUDE    float64
ELEVATION    float64
DATE          object
DAPR         float64
MDPR         float64
PRCP         float64
SNOW         float64
SNWD         float64
DASF         float64
MDSF         float64
dtype: object

In [11]:
df_seattle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7003 entries, 0 to 7002
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    7003 non-null   object
 1   NAME       7003 non-null   object
 2   LATITUDE   7003 non-null   float64
 3   LONGITUDE  7003 non-null   float64
 4   ELEVATION  7003 non-null   float64
 5   DATE       7003 non-null   object
 6   DAPR       143 non-null    float64
 7   MDPR       143 non-null    float64
 8   PRCP       6718 non-null   float64
 9   SNOW       3006 non-null   float64
 10  SNWD       1331 non-null   float64
 11  DASF       0 non-null      float64
 12  MDSF       0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 711.4+ KB

In [12]:
df_ny.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17465 entries, 0 to 17464
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    17465 non-null  object
 1   NAME       17465 non-null  object
 2   LATITUDE   17465 non-null  float64
 3   LONGITUDE  17465 non-null  float64
 4   ELEVATION  17465 non-null  float64
 5   DATE       17465 non-null  object
 6   DAPR       155 non-null    float64
 7   MDPR       151 non-null    float64
 8   PRCP       17275 non-null  float64
 9   SNOW       11508 non-null  float64
 10  SNWD       6318 non-null   float64
 11  DASF       0 non-null      float64
 12  MDSF       0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 1.7+ MB

In [13]:
df_seattle["NAME"].unique()

array(['SEATTLE 4.5 N, WA US', 'SEATTLE 6.5 SSW, WA US',
       'SEATTLE 3.9 SSW, WA US', 'SEATTLE 4.2 N, WA US',
       'SEATTLE 5.6 N, WA US', 'SEATTLE 2.1 ESE, WA US',
       'SEATTLE TACOMA AIRPORT, WA US', 'SEATTLE 5.8 SSE, WA US',
       'SEATTLE 5.5 NNE, WA US', 'SEATTLE 2.5 SE, WA US'], dtype=object)

In [14]:
df_ny["NAME"].unique()

array(['NY CITY CENTRAL PARK, NY US', 'ARMONK 0.3 SE, NY US',
       'WANTAGH 0.3 ESE, NY US', 'FARMINGDALE REPUBLIC AIRPORT, NY US',
       'ALBERTSON 0.2 SSE, NY US', 'JFK INTERNATIONAL AIRPORT, NY US',
       'AMITYVILLE 0.1 WSW, NY US', 'FLORAL PARK 0.4 W, NY US',
       'CENTERPORT 0.9 SW, NY US', 'BRIARCLIFF MANOR 1.3 NE, NY US',
       'QUEENS 4.7 SW, NY US', 'THORNWOOD 0.7 NW, NY US',
       'STATEN ISLAND 2.6 N, NY US',
       'MATTHEWS PALMER PLAYGROUND NEW YORK 6.8 NNW, NY US',
       'NEW HEMPSTEAD 0.6 SE, NY US', 'LITTLE NECK 0.3 SE, NY US',
       'ALBERTSON 0.5 SW, NY US', 'SPRING VALLEY 1.7 SSW, NY US',
       'LINDENHURST 1.0 NE, NY US', 'EAST ROCKAWAY 0.5 S, NY US'],
      dtype=object)

The data sets appear to be very similar, which is good.

The only problems are:
*   The Seattle data is missing some days.
*   The New York data has one more day then should be possible.
*   The New York data set has more weather stations than the Seattle data set.
*   The datatype of 'DATE' for both sets is not datetime.

## Convert Data Types
Let's convert 'DATE' to a datetime for both sets.

In [15]:
df_seattle["DATE"] = pd.to_datetime(df_seattle["DATE"])
df_seattle.dtypes

STATION              object
NAME                 object
LATITUDE            float64
LONGITUDE           float64
ELEVATION           float64
DATE         datetime64[ns]
DAPR                float64
MDPR                float64
PRCP                float64
SNOW                float64
SNWD                float64
DASF                float64
MDSF                float64
dtype: object

In [16]:
df_ny["DATE"] = pd.to_datetime(df_ny["DATE"])
df_ny.dtypes

STATION              object
NAME                 object
LATITUDE            float64
LONGITUDE           float64
ELEVATION           float64
DATE         datetime64[ns]
DAPR                float64
MDPR                float64
PRCP                float64
SNOW                float64
SNWD                float64
DASF                float64
MDSF                float64
dtype: object

## Remove Unnecessary Columns
We're not interested in many of the columns. We can simply drop them.

In [17]:
bad_cols = ["LATITUDE", "LONGITUDE", "ELEVATION", "DAPR", "MDPR", "SNOW", "SNWD", "DASF", "MDSF"]
df_seattle = df_seattle.drop(columns=bad_cols)
df_ny = df_ny.drop(columns=bad_cols)

## Remove Duplicate Entries and Drop NaNs
This code drops duplicates (if any exist) and we'll also drop any rows that have and NaN values. Note that many columns have been dropped already, so we are only dropping rows that have NaN for 'STATION', 'NAME', 'DATE', or 'PRCP'.

In [18]:
df_seattle = df_seattle.drop_duplicates(subset="DATE")
df_ny = df_ny.drop_duplicates(subset="DATE")

In [19]:
df_seattle = df_seattle.dropna()
df_ny = df_ny.dropna()

## Convert Data into Average PRCP by Day

In [20]:
df_seattle = df_seattle.groupby(by="DATE", as_index=False)["PRCP"].mean()
df_ny = df_ny.groupby(by="DATE", as_index=False)["PRCP"].mean()

## Rename Columns and Join Tables
This code renames the columns in each table so that when they are joined, it is clear which precipitation value came from which city. The code then joins them into a single table. Note that this merge will result in only the dates that are present in the seattle data appearing in the final table.

In [21]:
df_seattle = df_seattle.rename(columns={"DATE": "date", "PRCP": "seattle_precipitation"})
df_ny = df_ny.rename(columns={"DATE": "date", "PRCP": "ny_precipitation"})
# Note that this merge will result in only the dates that are present in the seattle data
df = df_seattle.merge(df_ny)

In [22]:
df

           date  seattle_precipitation  ny_precipitation
0    2020-01-01                   0.19              0.00
1    2020-01-02                   0.34              0.00
2    2020-01-03                   0.26              0.21
3    2020-01-04                   0.20              0.12
4    2020-01-05                   0.14              0.00
...         ...                    ...               ...
1378 2023-12-27                   0.00              0.00
1379 2023-12-28                   0.26              2.16
1380 2023-12-29                   0.08              0.00
1381 2023-12-30                   0.02              0.00
1382 2023-12-31                   0.06              0.01

[1383 rows x 3 columns]

The table looks as expected. Let's export it.

## Export Data
The following code exports our clean data frame to a csv, and then copies it into the user's google drive.

In [23]:
df.to_csv('clean_seattle_nyc_weather.csv', index=False)

In [24]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [25]:
!cp clean_seattle_nyc_weather.csv "drive/My Drive/"